# Generated by Django 4.2.7 on 2023-11-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('duracao', models.TimeField()),
                ('diretor', models.CharField(max_length=100)),
                ('ano_de_lancamento', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=30)),
                ('pais_de_origem', models.CharField(choices=[('US', 'Estados Unidos'), ('CA', 'Canadá'), ('CN', 'China'), ('GB', 'Reino Unido'), ('JP', 'Japão'), ('IN', 'Índia'), ('KR', 'Coréia do Sul'), ('FR', 'França'), ('NG', 'Nigéria'), ('BR', 'Brasil'), ('IT', 'Itália'), ('AU', 'Austrália'), ('DE', 'Alemanha'), ('RU', 'Rússia'), ('ES', 'Espanha')], default='BR', max_length=2)),
                ('idioma', models.CharField(choices=[('EN', 'Inglês'), ('FR', 'Francês'), ('ZH', 'Chinês'), ('HI', 'Hindi'), ('JA', 'Japonês'), ('KO', 'Coreano'), ('ES', 'Espanhol'), ('PT', 'Português'), ('IT', 'Italiano'), ('DE', 'Alemão'), ('RU', 'Russo'), ('AR', 'Árabe')], default='PT', max_length=2)),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bilheteria', models.DecimalField(decimal_places=2, max_digits=15)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.URLField()),
                ('elenco', models.ManyToManyField(related_name='filmes', to='app.ator')),
            ],
        ),
    ]
