# Generated by Django 4.2.7 on 2023-11-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ator',
            options={'verbose_name_plural': 'Ator'},
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'verbose_name_plural': 'Filmes'},
        ),
    ]
