# Generated by Django 4.2.7 on 2023-11-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_diretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor'),
        ),
    ]
