# Generated by Django 4.2.7 on 2023-11-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_classificacao_alter_filme_classificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ator',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Ator'},
        ),
        migrations.AlterModelOptions(
            name='classificacao',
            options={'ordering': ['classificacao'], 'verbose_name_plural': 'Classificação'},
        ),
        migrations.AlterModelOptions(
            name='diretor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Diretor'},
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Gênero'},
        ),
    ]
