# Generated by Django 4.2.7 on 2023-11-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ator_options_alter_classificacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
